os:
  - linux

language: go

addons:
    artifacts:
        debug: true
        paths:
        - $GOPATH/bin

dist: trusty

services:
  - docker

go:
    - 1.8

script:
    - set -e
# Run tests
    - go test github.com/honeycombio/honeyaws/...
# Build binary and packages
    - go install -ldflags "-X main.BuildID=1.${TRAVIS_BUILD_NUMBER}" github.com/honeycombio/honeyaws/cmd/...
    - ./build-pkg.sh -v "1.${TRAVIS_BUILD_NUMBER}" -t deb
    - ./build-pkg.sh -v "1.${TRAVIS_BUILD_NUMBER}" -t rpm
# Check that packages install
    - pkg-test/test.sh "1.${TRAVIS_BUILD_NUMBER}"

before_install:
    # Install fpm for deb/rpm package building
    - sudo apt-get -qq update
    - sudo apt-get install -y build-essential rpm
    - gem install fpm

install:
        - true # HACK: fixes travis-CI lack of support for vendor/ + godeps

after_success:
  - set -e
  - if [[ "${TRAVIS_BRANCH}" == "master" && "${TRAVIS_PULL_REQUEST}" == false ]]; then
      docker build -t honeycombio/honeyaws:latest .;
      docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD};
      docker tag honeycombio/honeyaws:latest honeycombio/honeyaws:1.${TRAVIS_BUILD_NUMBER};
      docker push honeycombio/honeyaws:latest;
      docker push honeycombio/honeyaws:1.${TRAVIS_BUILD_NUMBER};
    fi;
