version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.13
  docker: circleci/docker@1.3.0

jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - run: go test --timeout 10s -v ./...

  build_packages:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - run: o install -ldflags "-X main.BuildID=${CIRCLE_TAG}" github.com/honeycombio/honeyaws/cmd/...
      - setup_remote_docker
      - run:
          name: apt_get_update
          command: sudo apt-get -qq update
      - run:
          name: apt_get_install
          command: sudo apt-get install -y build-essential rpm ruby ruby-dev
      - run:
          name: gem_install
          command: sudo gem install fpm
      - run: mkdir -p ~/artifacts
      - run:
          name: build_deb
          command: ./build-pkg.sh -v `echo -n "${CIRCLE_TAG}" | sed 's/v//g'` -t deb && cp $GOPATH/bin/honeyaws_${CIRCLE_TAG}_amd64.deb ~/artifacts
      - run:
          name: build_rpm
          command: ./build-pkg.sh -v `echo -n "${CIRCLE_TAG}" | sed 's/v//g'` -t rpm && cp $GOPATH/bin/honeyaws-${CIRCLE_TAG}-1.x86_64.rpm ~/artifacts
      - run: pkg-test/test.sh "${CIRCLE_TAG}"
      - run: echo "finished builds" && find ~/artifacts -ls
      - persist_to_workspace:
          root: ~/
          paths:
            - artifacts
      - store_artifacts:
          path: ~/artifacts

  publish_github:
    docker:
      - image: cibuilds/github:0.13.0
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: "Publish Release on GitHub"
          command: |
            echo "about to publish to tag ${CIRCLE_TAG}"
            ls -l ~/artifacts/*
            ghr -draft -n ${CIRCLE_TAG} -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} ${CIRCLE_TAG} ~/artifacts

  publish_s3:
    executor: aws-cli/default
    steps:
      - attach_workspace:
          at: ~/
      - aws-cli/install
      - aws-cli/configure:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_REGION
      - run:
          name: sync_s3_artifacts
          command: aws s3 sync ~/artifacts s3://honeycomb-builds/honeycombio/honeyaws/${CIRCLE_TAG}/

workflows:
  version: 2
  build:
    jobs:
      - build
      - build_packages:
          requires:
            - build
      - publish_github:
          context: Honeycomb Secrets for Public Repos
          requires:
            - build_packages
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - publish_s3:
          context: Honeycomb Secrets for Public Repos
          requires:
            - build_packages
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - docker/publish:
          tag: latest,${CIRCLE_TAG:1}
          extra_build_args: --build-arg BUILD_ID=${CIRCLE_TAG:1}
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          requires:
            - build_packages
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
