version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.13
  docker: circleci/docker@1.3.0

commands:
  go-build:
    parameters:
      os:
        description: Target operating system
        type: enum
        enum: ["linux", "darwin"]
        default: "linux"
      arch:
        description: Target architecture
        type: enum
        enum: ["amd64", "arm64"]
        default: "amd64"
    steps:
      - run: |
          GOOS=<< parameters.os >> \
          GOARCH=<< parameters.arch >> \
          cd cmd/honeyalb && go build -ldflags "-X main.BuildID=v1.4.0" \
          -o $GOPATH/bin/honeyalb-<< parameters.os >>-<< parameters.arch >> \
          .
      - run: |
          GOOS=<< parameters.os >> \
          GOARCH=<< parameters.arch >> \
          cd cmd/honeyelb && go build -ldflags "-X main.BuildID=v1.4.0" \
          -o $GOPATH/bin/honeyelb-<< parameters.os >>-<< parameters.arch >> \
          .
      - run: |
          GOOS=<< parameters.os >> \
          GOARCH=<< parameters.arch >> \
          cd cmd/honeycloudfront && go build -ldflags "-X main.BuildID=v1.4.0" \
          -o $GOPATH/bin/honeycloudfront-<< parameters.os >>-<< parameters.arch >> \
          .
      - run: |
          GOOS=<< parameters.os >> \
          GOARCH=<< parameters.arch >> \
          cd cmd/honeycloudtrail && go build -ldflags "-X main.BuildID=v1.4.0" \
          -o $GOPATH/bin/honeycloudtrail-<< parameters.os >>-<< parameters.arch >> \
          .

jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - run: go test --timeout 10s -v ./...

  build_packages:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - run: go install -ldflags "-X main.BuildID=v1.4.0" github.com/honeycombio/honeyaws/cmd/...
      - setup_remote_docker
      - run:
          name: apt_get_update
          command: sudo apt-get -qq update
      - run:
          name: apt_get_install
          command: sudo apt-get install -y build-essential rpm ruby ruby-dev
      - run:
          name: gem_install
          command: sudo gem install fpm
      - run: mkdir -p ~/artifacts
      - run:
          name: build_deb
          command: CIRCLE_TAG=`echo -n "v1.4.0" | sed 's/v//g'` && ./build-pkg.sh -v "${CIRCLE_TAG}" -t deb && cp $GOPATH/bin/honeyaws_${CIRCLE_TAG}_amd64.deb ~/artifacts
      - run:
          name: build_rpm
          command: CIRCLE_TAG=`echo -n "v1.4.0" | sed 's/v//g'` && ./build-pkg.sh -v "${CIRCLE_TAG}" -t rpm && cp $GOPATH/bin/honeyaws-${CIRCLE_TAG}-1.x86_64.rpm ~/artifacts
      - run: pkg-test/test.sh `echo -n "v1.4.0" | sed 's/v//g'`
      - go-build:
          os: linux
          arch: amd64
      - go-build:
          os: linux
          arch: arm64
      - go-build:
          os: darwin
          arch: amd64
      - run: cp $GOPATH/bin/honey* ~/artifacts
      - run: echo "finished builds" && find ~/artifacts -ls
      - persist_to_workspace:
          root: ~/
          paths:
            - artifacts
      - store_artifacts:
          path: ~/artifacts

  publish_github:
    docker:
      - image: cibuilds/github:0.13.0
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: "Publish Release on GitHub"
          command: |
            echo "about to publish to tag ${CIRCLE_TAG}"
            ls -l ~/artifacts/*
            ghr -draft -n ${CIRCLE_TAG} -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} ${CIRCLE_TAG} ~/artifacts

  publish_s3:
    executor: aws-cli/default
    steps:
      - attach_workspace:
          at: ~/
      - aws-cli/install
      - aws-cli/configure:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_REGION
      - run:
          name: sync_s3_artifacts
          command: aws s3 sync ~/artifacts s3://honeycomb-builds/honeycombio/honeyaws/v1.4.0/

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - build_packages:
          requires:
            - build
          filters:
            tags:
              only: /^v[0-9].*/
      - publish_github:
          context: Honeycomb Secrets for Public Repos
          requires:
            - build_packages
          filters:
            tags:
              only: /^v[0-9].*/
            branches:
              ignore: /.*/
      - publish_s3:
          context: Honeycomb Secrets for Public Repos
          requires:
            - build_packages
          filters:
            tags:
              only: /^v[0-9].*/
      - docker/publish:
          tag: latest,${CIRCLE_TAG:1}
          extra_build_args: --build-arg BUILD_ID=${CIRCLE_TAG:1}
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          requires:
            - build_packages
          filters:
            tags:
              only: /^v[0-9].*/
            branches:
              ignore: /.*/
