name: Sync Github Issue to Asana
on:
  issues:
    types: [opened]

jobs:
  create-asana-task:
    runs-on: ubuntu-latest

    steps:
      - name: Create Asana task
        uses: honeycombio/gha-create-asana-task@v1.0.0
        with:
          asana-secret: ${{ secrets.ASANA_PAT }}
          asana-workspace-id: ${{ secrets.ASANA_WORKSPACE_ID }}
          asana-project-id: ${{ secrets.ASANA_PROJECT_ID }}
          asana-section-id: ${{ secrets.ASANA_SECTION_ID }}
          asana-tags: '["1203366051961930", "1170327382493643"]' # adds the tags interrupt and oncall
          asana-task-name: '${{ github.event.repository.name }}: ${{ github.event.issue.title }}'
          asana-task-description: |
            ${{ github.event.issue.body }}
            source: https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}/issues/${{ github.event.issue.number }}
